# Generated by Django 5.1.7 on 2025-03-31 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('advisor', 'Advisor'), ('customer', 'Customer')], default='customer', max_length=10),
        ),
    ]
