# Generated by Django 5.1.7 on 2025-03-27 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisorVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'ממתין לאישור'), ('approved', 'מאושר'), ('rejected', 'נדחה')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('advisor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_verifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdvisorQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_years', models.IntegerField(help_text='שנות ניסיון בתחום הייעוץ')),
                ('education', models.TextField(help_text='השכלה רלוונטית')),
                ('certifications', models.TextField(help_text='תעודות והסמכות רלוונטיות')),
                ('expertise_areas', models.TextField(help_text='תחומי התמחות ספציפיים')),
                ('previous_clients', models.TextField(help_text='תיאור ניסיון עם לקוחות קודמים')),
                ('methodology', models.TextField(help_text='מתודולוגיית הייעוץ שלך')),
                ('availability', models.TextField(help_text='זמינות וסגנון עבודה')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire', to='myapp.advisorverification')),
            ],
        ),
        migrations.CreateModel(
            name='AdvisorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('certification', 'תעודת הסמכה'), ('education', 'תעודת השכלה'), ('experience', 'אישור ניסיון'), ('id', 'תעודת זהות'), ('other', 'אחר')], max_length=20)),
                ('file', models.FileField(upload_to='advisor_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='myapp.advisorverification')),
            ],
        ),
    ]
