# Generated by Django 5.1.7 on 2025-03-31 18:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional_title', models.CharField(max_length=100)),
                ('years_of_experience', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('specialization', models.CharField(max_length=200)),
                ('education', models.TextField(validators=[django.core.validators.MinLengthValidator(50)])),
                ('certifications', models.TextField(blank=True)),
                ('about', models.TextField(validators=[django.core.validators.MinLengthValidator(100)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advisor_application', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
