# Generated by Django 5.1.7 on 2025-03-27 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_advisorverification_advisorquestionnaire_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisorquestionnaire',
            name='verification',
        ),
        migrations.RemoveField(
            model_name='advisorverification',
            name='advisor',
        ),
        migrations.RemoveField(
            model_name='advisorverification',
            name='reviewed_by',
        ),
        migrations.DeleteModel(
            name='AdvisorDocument',
        ),
        migrations.DeleteModel(
            name='AdvisorQuestionnaire',
        ),
        migrations.DeleteModel(
            name='AdvisorVerification',
        ),
    ]
