# Generated by Django 5.1.7 on 2025-03-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_advisorquestionnaire_verification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Enter phone number with country code (e.g., +972501234567)', max_length=15, null=True),
        ),
    ]
