# Generated by Django 5.0.6 on 2024-06-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_followee_follow_followerss_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image for the post.', null=True, upload_to='posts/'),
        ),
    ]
