# Generated by Django 5.0.3 on 2024-04-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_userprofile_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_imag_container',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_profile_imag',
            field=models.URLField(blank=True, null=True),
        ),
    ]
