# Generated by Django 5.0.6 on 2024-06-11 14:48

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
