# Generated by Django 5.0.6 on 2024-06-11 15:03

import myapp.models.UserprofileFolder.userprofile_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_userprofile_user_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_image_container',
            field=models.ImageField(blank=True, default=myapp.models.UserprofileFolder.userprofile_model.default_image, null=True, upload_to=myapp.models.UserprofileFolder.userprofile_model.user_directory_path),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_profile_image',
            field=models.ImageField(blank=True, default=myapp.models.UserprofileFolder.userprofile_model.default_image, null=True, upload_to=myapp.models.UserprofileFolder.userprofile_model.user_directory_path),
        ),
    ]
