# Generated by Django 5.0.3 on 2024-04-10 18:41

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_userprofile_groups_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_imag_container',
            new_name='user_image_container',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_profile_imag',
            new_name='user_profile_image',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_birth_date',
            field=models.DateField(default=myapp.models.default_date, help_text='Enter your birth date in the format: YYYY-MM-DD', validators=[myapp.models.validate_birth_date]),
        ),
    ]
