# Generated by Django 5.0.6 on 2024-06-16 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_userprofile_user_image_container_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='userID',
        ),
    ]
