# Generated by Django 5.0.6 on 2024-06-16 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_user_userprofile_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='userID',
            new_name='user',
        ),
    ]
