# Generated by Django 5.0.6 on 2024-06-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_userid_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recording_url', models.URLField(blank=True, null=True)),
                ('transcript', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
