# Generated by Django 5.0.6 on 2024-06-26 17:38

import django.db.models.deletion
import myapp.models.UserprofileFolder.userprofile_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_meeting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_image_container',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_profile_image',
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_image_container', models.ImageField(blank=True, default=myapp.models.UserprofileFolder.userprofile_model.default_image, null=True, upload_to=myapp.models.UserprofileFolder.userprofile_model.user_directory_path)),
                ('user_profile_image', models.ImageField(blank=True, default=myapp.models.UserprofileFolder.userprofile_model.default_image, null=True, upload_to=myapp.models.UserprofileFolder.userprofile_model.user_directory_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.userprofile')),
            ],
        ),
    ]
