# Generated by Django 5.0.3 on 2024-05-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_datamodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.FloatField(help_text='Total size of the database in MB')),
                ('free_space', models.FloatField(help_text='Free space in the database in MB')),
                ('used_space', models.FloatField(help_text='Used space in the database in MB')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='The last time the database info was updated')),
            ],
        ),
        migrations.DeleteModel(
            name='DataModel',
        ),
    ]
