# Generated by Django 5.0.6 on 2024-06-27 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_userprofile_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_country',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
