# Generated by Django 5.0.6 on 2024-06-28 00:12

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_userprofile_user_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
