# Generated by Django 5.0.3 on 2024-05-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_databaseinfo_delete_datamodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databaseinfo',
            name='last_updated',
        ),
        migrations.AlterField(
            model_name='databaseinfo',
            name='free_space',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='databaseinfo',
            name='size',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='databaseinfo',
            name='used_space',
            field=models.FloatField(),
        ),
    ]
