# Generated by Django 5.0.3 on 2024-05-12 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_databaseinfo_last_updated_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DatabaseInfo',
        ),
    ]
