# Generated by Django 5.0.6 on 2024-06-29 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_userprofile_user_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_phone',
        ),
    ]
