# Generated by Django 5.0.6 on 2024-06-29 15:09

import django.db.models.deletion
import myapp.models.UserprofileFolder.userprofile_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_userprofile_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='image_subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myapp.userprofile'),
        ),
        migrations.AlterField(
            model_name='images',
            name='user_image_container',
            field=models.ImageField(blank=True, default=myapp.models.UserprofileFolder.userprofile_model.default_image, null=True, upload_to=myapp.models.UserprofileFolder.userprofile_model.user_directory_path, validators=[myapp.models.UserprofileFolder.userprofile_model.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='images',
            name='user_profile_image',
            field=models.ImageField(blank=True, default=myapp.models.UserprofileFolder.userprofile_model.default_image, null=True, upload_to=myapp.models.UserprofileFolder.userprofile_model.user_directory_path, validators=[myapp.models.UserprofileFolder.userprofile_model.validate_image_file_size]),
        ),
    ]
