# Generated by Django 5.0.3 on 2024-05-27 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_delete_databaseinfo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_country',
            field=models.CharField(choices=[('USA', 'USA'), ('UK', 'UK'), ('CAN', 'CAN'), ('AUS', 'AUS'), ('IND', 'IND'), ('GER', 'GER'), ('FRA', 'FRA'), ('ITA', 'ITA'), ('SPA', 'SPA'), ('BRA', 'BRA'), ('JPN', 'JPN'), ('CHN', 'CHN'), ('RUS', 'RUS'), ('MEX', 'MEX'), ('ARG', 'ARG'), ('COL', 'COL'), ('PER', 'PER'), ('CHI', 'CHI'), ('IL', 'IL'), ('EGY', 'EGY')], default='', help_text='Select your country.', max_length=3),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='', help_text='Select your gender.', max_length=1),
        ),
        migrations.CreateModel(
            name='ActivateAccount_Email',
            fields=[
                ('activation_id', models.AutoField(help_text='The ID of the activation email.', primary_key=True, serialize=False)),
                ('activation_key', models.CharField(help_text='The activation key for the account.', max_length=40)),
                ('activation_date', models.DateTimeField(auto_now_add=True, help_text='The date when the activation email was sent.')),
                ('is_activated', models.BooleanField(default=False, help_text='Check this if the account has been activated.')),
                ('user', models.ForeignKey(help_text='Select the user who will activate the account.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
