# Generated by Django 5.0.3 on 2024-05-27 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_userprofile_user_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activateaccount_email',
            old_name='is_activated',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='activateaccount_email',
            old_name='user',
            new_name='username',
        ),
    ]
