# Generated by Django 5.0.6 on 2024-06-29 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='user_image_container',
        ),
    ]
