# Generated by Django 5.0.6 on 2024-06-29 17:52

import myapp.models.UserprofileFolder.userprofile_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_remove_images_user_image_container'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='user_image_container',
            field=models.ImageField(blank=True, default=myapp.models.UserprofileFolder.userprofile_model.default_image, null=True, upload_to=myapp.models.UserprofileFolder.userprofile_model.user_directory_path, validators=[myapp.models.UserprofileFolder.userprofile_model.validate_image_file_size]),
        ),
    ]
