# Generated by Django 5.0.6 on 2024-06-29 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_images_user_image_container'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='user_profile_image',
        ),
    ]
